server:
  port: 9100

spring:
  application:
    name: musala-drones-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs