spring:
  application:
    name: musala-drones-service
  datasource:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:dronesdb
    username: sa
    password: password
  h2.console:
    enabled: true
    path: /h2
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/Changelog.xml
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 9100
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
musala:
  auto-sync-cron: 0 0 5 * * *
